import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "./components/banner/banner";
import Header from "./components/header/header";
import Navbar from "./components/navbar/navbar"
import Footer from "./footer/footer";
import { CartProvider } from "./context/cartcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
        <Banner></Banner>
        <Header></Header>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </CartProvider>
      </body>
    </html>
  );
}
